########################################################################################################################
################################################# markets configuration ################################################
########################################################################################################################

lem_continuous:                       # name of the market (must be unique in its region)
                                      # note: markets with the same name can trade among each other if specified
  active: True                        # is the market active?
                                      # options:
                                      #   - True: market is active
                                      #   - False: market is inactive (market is ignored in simulation)

  type: lem                           # type of the market
                                      # options:
                                      #   - lem: local energy market

  clearing:
    type: ex-ante                     # type of market clearing
                                      # options:
                                      #   - ex-ante: market clearing is done before the delivery period
                                      #   - TODO ex-post: market clearing is done after the delivery period
                                      #   - None: no market clearing is done (all energy is purchased from retailer)

    method: pda                       # method of market clearing
                                      # options:
                                      #   - pda: periodic double auction
                                      #   - community: community clearing
                                      # note: for further information about the method options see the documentation

    pricing: uniform                  # pricing method of the market clearing
                                      # options:
                                      #   - uniform (ex-ante): all participants pay the same price
                                      #   - discriminatory (ex-ante): each participant pays a different price
                                      #   - standard (ex-post): see details in the ex-post folder
                                      # note: for further information about the pricing options see the documentation

    coupling: above_l                 # method of coupling market regions (are uncleared positions posted elsewhere?)
                                      # options:
                                      #   - None: unsettled bids are not offered at other markets, i.e. bids get feed-in tariff and offers pay retail wholesale price
                                      #   - above_c: unsettled bids are continuously offered at higher market levels (if possible)
                                      #   - above_l: unsettled bids are offered at higher market levels in the last clearing period (if possible)
                                      #   - below_c: unsettled bids are continuously offered at lower market levels (if possible)
                                      #   - below_l: unsettled bids are offered at lower market levels in the last clearing period (if possible)


    timing:                           # timing of the market
      start: 0                        # start of the market in unix time with timezone information
                                      #   - unix time: market starts at the specified time
                                      #       format (ISO 8601): %Y-%m-%dT%H:%M:%S%z (YYYY-MM-DDTHH:MM:SS+HH:MM)
                                      #   - timedelta: specify the distance to the start of the simulation
                                      #       unit: seconds


      opening: 3600                    # when does the first auction occur after the first delivery period
                                      # unit: seconds

      horizon: [0, 86400]             # horizon of the market clearings (at what time range is energy delivered?)
                                      # unit: seconds
                                      # note: first position is for the start of the horizon, second for the end
                                      #   which will be excluded in the horizon (e.g. 0 <= x < 86400)
                                      # note: if the horizon is longer than the duration of the market clearing
                                      #   period, the market clearing period is repeated until the horizon is
                                      #   covered and vice versa.

      duration: 3600                   # duration of one energy delivery period
                                      # unit: seconds

      frequency: 3600                  # how often is ex-ante market clearing executed?
                                      # unit: seconds

      closing: 3600                      # when does the last auction occur before the delivery period
                                      # unit: seconds

      settling: 'continuous'          # at which time steps is the market settled?
                                      # options:
                                      #   - continuous: market is settled at every first time step once horizon is passed
                                      #   - period: market is settled for the entire period

  pricing:                            # pricing of each retailer
                                      # note: currently only one retailer is possible
    retailer:                         # name of the retailer
                                      # note: currently only one retailer possible
      energy:                         # parameters for retail energy (if market is ex-ante)
        method: fixed                 # how should retail prices be determined?
                                      # options:
                                      #   - fixed: prices as defined by 'fixed' parameter
                                      #   - file: prices contained in file provided by 'file' parameter

        fixed:                        # fixed retail energy settings (retailer market offers from the agents' view)
          'price': [0.0827, 0.147]       # retail energy prices
                                      # unit: €/kWh
                                      # note: first position is for selling to, second for buying energy from retailer

          'quantity': [1e6, 1e6]      # retail energy quantities
                                      # unit: Wh
                                      # note: first position is for selling, second for buying energy

          quality: 0                  # quality that the offered energy should be labelled with on the lem
                                      # note: the value needs to match the index of one of the values under types/qualities

        file:
          file: lem_continuous_energy.csv  # file containing the energy prices and quantities for each time step

      grid:                           # parameters for grid fees
                                      # explanation: logic behind it is that the grid fees are always added to the
                                      #   energy traded at that market level and if the energy is traded at a higher
                                      #   market level, the grid fees are added to the energy price. This way the
                                      #   different sources of energy can be considered in price (but not in terms of
                                      #   quality). If the energy is procured from the retailer, the wholesale fee is
                                      #   used instead of the local one.
        method: fixed                 # how should balancing energy prices be set?
                                      # options:
                                      #   - fixed: prices as defined by 'fixed' parameter
                                      #   - file: prices contained in file provided by 'file' parameter
                                      # balancing energy is the market participants deviation from the market
                                      # result. the balancing price is the incentive for the agent to stick
                                      # to the market result, or to assist the system in restoring its balance

        fixed:                        # fixed grid fees settings
          local: [0, 0.10]            # local grid fees (applies to this market)
                                      # unit: €/kWh
                                      # note: first position is for selling, second for buying energy

          retail: [0, 0.10]           # retail grid fees (applies to energy purchased form/sold to retailer)
                                      # unit: €/kWh
                                      # note: first position is for selling, second for buying energy


        file:                         # file grid fees settings
          file: grid_1.csv            # file containing the grid fees for each time step
                                      # note: columns need to match the names of the parameters in the 'fixed' section

      levies:                         # parameters for levies
        method: fixed                 # how should levies be set?
                                      # options:
                                      #   - fixed: prices as defined by 'fixed' parameter
                                      #   - file: prices contained in file provided by 'file' parameter
                                      # note: levies are taxes that are added to the energy price

        fixed:                        # fixed levies settings
          price: [0, 0.1297]            # price of the levies
                                      # unit: €/kWh
                                      # note: first position is for selling, second for buying energy

        file:
          file: levies_1.csv          # file containing the levies for each time step
                                      # note: columns need to match the names of the parameters in the 'fixed' section

      balancing:                      # parameters for balancing energy
                                      # note: balancing energy is the market participants deviation from the market
                                      #   result. The balancing price is the cost of either buying or selling energy
                                      #   to the grid to restore the balance of the system and serves as an incentive
                                      #   for the market participants to stick to the market result.
                                      # note: balancing costs are not added to the energy but separate. This needs to
                                      #   be considered when setting the balancing prices.
        method: fixed                 # how should balancing energy prices be set?
                                      # options:
                                      #   - fixed: prices as defined by 'fixed' parameter
                                      #   - file: prices contained in file provided by 'file' parameter

        fixed:                        # fixed balancing settings
          price: [0.0727, 0.157]         # balancing energy prices
                                      # unit: €/kWh
                                      # note: first position is for selling, second for buying energy

          quantity: [1e6, 1e6]        # balancing energy quantities
                                      # unit: Wh
                                      # note: first position is for selling, second for buying energy
                                      # note: the quantities cancel each other out and are therefore net amounts


        file:                         # file balancing settings
          file: balancing_1.csv       # file containing the balancing energy prices for each time step
                                      # note: columns need to match the names of the parameters in the 'fixed' section