import os
import matplotlib.pyplot as plt


class PlotterBase:
    def __init__(self, path: dict, config: dict, name_subdirectory: str, data_processor):
        # Configuration dictionary
        self.config = config

        # Data processor
        self.data_processor = data_processor

        # Plotted figures
        self.figures = {}

        # subdirectory name
        self.name_subdirectory = name_subdirectory

        # Combine normal path and subdirectory path
        self.path = {}
        for path_key, value in path.items():
            self.path[path_key] = os.path.join(value, self.name_subdirectory)

    def plot_all(self, **kwargs):
        """Plot all relevant results data."""
        # get all plot data functions, function has to start with 'plot_' to be included
        plot_functions = [func for func in dir(self) if (callable(getattr(self, func)) and
                          getattr(getattr(self, func), 'is_plot', False))]

        self.run_plots(plot_functions, **kwargs)

    def run_plots(self, plot_functions, **kwargs):
        """Run every plot, then raise whatever failed.

        Both halves matter. **Every plot is attempted**, because one failing must not cost the
        others -- that is why the failures are collected rather than raised at the first. And
        **they are raised**, not printed: printing them meant `Analyzer.plot_all()` could not fail
        whatever happened underneath, so `plot_electricity_grid_topology` sat broken for the whole
        life of the module in three independent ways (an undeclared `igraph`, a hardcoded grid
        filename, and a results path missing a directory component) and nothing ever said so. See
        #228.

        Raised as an `ExceptionGroup` so a caller sees all of them with their tracebacks intact,
        rather than the first one standing in for the rest.
        """
        failures = {}
        for func in plot_functions:
            try:
                getattr(self, func)(**kwargs)
            except Exception as error:  # noqa: BLE001 - re-raised in the group below
                failures[func] = error

        if failures:
            raise ExceptionGroup(
                f'{len(failures)} of {len(plot_functions)} plots failed in '
                f'{type(self).__name__}: {sorted(failures)}',
                list(failures.values()))

    def get_plotting_data(self, data_name, **kwargs):
        """
        Retrieve or process data for plotting. If the requested data is not already stored in the data processor, it is
        processed using the corresponding method and then stored.

        Args:
            data_name (str): The name of the data to retrieve or process.

        Returns:
            Any: The processed or retrieved data associated with `data_name`.
        """
        # Check if the requested data is already available in the data processor
        if data_name not in self.data_processor.data.keys():
            # If not, generate the processing method name dynamically and call it
            self.data_processor.data[data_name] = (getattr(self.data_processor, '_'.join(['process', data_name]))
                                                   (**kwargs))

        # Return the processed or retrieved data
        return self.data_processor.data[data_name]


def decorator_plot_function(func):
    """
    Decorator to process and save plot figures generated by a function.

    Args:
        func (callable): The plotting function to decorate.

    Returns:
        callable: A wrapped function that processes and optionally saves the plot figures.
    """

    def func_wrapper(*args, **kwargs):
        result_figs = func(*args, **kwargs)  # Execute the function and get figures
        save_path = kwargs.get('save_path')

        if save_path:
            os.makedirs(save_path, exist_ok=True)  # Ensure save path exists

            if not isinstance(result_figs, dict):
                result_figs = {'': result_figs}

            for name, fig in result_figs.items():
                save_method = "savefig" if hasattr(fig, "savefig") else "write_image"
                getattr(fig, save_method)(
                    os.path.join(save_path, f"{name}_{func.__name__.replace('plot_', '')}.pdf"))

        plt.show()

        return func

    # add attribute 'is_plot' to make sure the function is identified as a plotting function
    setattr(func_wrapper, 'is_plot', True)

    return func_wrapper
