name: '📝 Other'
description: Use this template for any issue that doesn't fit the other templates.

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary of the Issue
      description: >
        Provide a clear and concise summary of the issue or question.
        **Example**: "There seems to be confusion regarding how to use the new scheduling feature, and it is causing delays."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: >
        Provide more details about the issue, including any background context that would be helpful.
        You can mention the areas or modules affected by this issue if applicable.
        **Example**: "The documentation for the scheduling feature doesn't explain how to handle time zones, which has led to scheduling errors."
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: >
        Describe what you expected to happen. This will help clarify the desired state or resolution.
        **Example**: "I expect the scheduling system to allow for time zone handling without manual adjustments."
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce or Example Use Case
      description: >
        If applicable, describe the steps you took that led to this issue, or explain a relevant use case scenario.
        **Example**: "Step 1: Set up a new event in the scheduler. Step 2: Assign it to a user in another time zone. The time doesn't adjust automatically."
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: >
        Provide any additional information that may help, such as screenshots, logs, or links to related documentation or issues.
    validations:
      required: false
