name: '🔒 Security vulnerability'
description: Report a security issue or vulnerability in the tool.
labels: [Type::Security]

body:
  - type: textarea
    id: vulnerability
    attributes:
      label: Vulnerability Description
      description: >
        Provide a detailed description of the vulnerability, including any known exploits or risks.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: >
        Provide step-by-step instructions on how to reproduce the vulnerability (if applicable).
    validations:
      required: false

  - type: textarea
    id: severity
    attributes:
      label: Severity and Impact
      description: >
        Describe the potential impact of the vulnerability, and how severe it is (e.g., low, medium, high).
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: Suggested Remediation
      description: >
        If known, provide possible fixes or remediations for the vulnerability.
    validations:
      required: false

  - type: checkboxes
    id: hot-fix
    attributes:
      label: Hot-fix Needed
      description: >
        Indicate if this vulnerability is critical enough to require an immediate hot-fix by selecting the corresponing label and ticking the checkox.
      options:
        - label: This issue is critical and needs a hot-fix.
          required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: >
        Add any other context or details about the vulnerability.
    validations:
      required: false
