"""Unit — the scenario format check itself.

A scenario folder generated by one version of the Creator and executed by another is not read
*wrongly*; it is read successfully and produces different numbers. The retailer in/out convention
fix is the case that motivated this: a scenario generated before it and run after it applies grid
fees and levies to feed-in, with no error and no warning.

So the check is a refusal, not a warning. When that was decided, a warning would additionally
have been *invisible* -- `hamlet/executor/setup.py` called `warnings.filterwarnings("ignore")` at
import. That filter is gone (#199) and a warning would now be seen, which removes the second
argument but not the first: reading a scenario in the wrong format produces wrong numbers, and a
message the user can scroll past is not a safeguard against that.
"""
import pytest

import hamlet.constants as c
import hamlet.functions as f
from hamlet.functions import ScenarioFormatError

CURRENT = c.SCENARIO_FORMAT_VERSION


def general(version=CURRENT):
    """A `general.json` as the Creator writes it, stamped with `version`."""
    return {c.K_SCENARIO_FORMAT_VERSION: version, 'structure': {'example': {}}}


class TestTheStampIsAccepted:

    def test_the_current_version_passes(self):
        assert f.check_scenario_format(general(), 'scenario') == CURRENT

    def test_it_does_not_depend_on_the_tool_version(self):
        """`VERSION` tracks HAMLET, this tracks the scenario folder; they must stay independent.

        If the two were the same number, every release would invalidate every scenario.
        """
        assert isinstance(CURRENT, int)


class TestAMissingStampIsRejected:
    """Absent means "generated before versioning existed", i.e. exactly the pre-fix case."""

    def test_a_scenario_without_a_stamp_is_refused(self):
        with pytest.raises(ScenarioFormatError):
            f.check_scenario_format({'structure': {}}, 'scenario')

    def test_the_message_names_the_remedy_and_not_only_the_mismatch(self):
        """Being told "version mismatch" and nothing else leaves the user stuck."""
        with pytest.raises(ScenarioFormatError) as error:
            f.check_scenario_format({'structure': {}}, 'scenario')

        message = str(error.value)
        assert 're-create this scenario' in message.lower()
        assert 'new_scenario_from_configs' in message
        assert 'allow_incompatible_scenario' in message

    def test_the_message_names_the_folder(self):
        with pytest.raises(ScenarioFormatError) as error:
            f.check_scenario_format({}, 'some/scenario/folder')

        assert 'some/scenario/folder' in str(error.value)

    def test_the_message_says_what_would_have_gone_wrong(self):
        """The user has to be able to judge whether their existing results are affected."""
        with pytest.raises(ScenarioFormatError) as error:
            f.check_scenario_format({}, 'scenario')

        assert 'feed-in' in str(error.value)


class TestAMismatchedStampIsRejected:

    def test_an_older_scenario_is_refused(self):
        with pytest.raises(ScenarioFormatError) as error:
            f.check_scenario_format(general(CURRENT - 1), 'scenario')

        assert str(CURRENT - 1) in str(error.value)
        assert str(CURRENT) in str(error.value)

    def test_a_newer_scenario_is_refused(self):
        """Written by a newer HAMLET than the one reading it -- the same hazard, reversed."""
        with pytest.raises(ScenarioFormatError) as error:
            f.check_scenario_format(general(CURRENT + 1), 'scenario')

        assert 'newer' in str(error.value)

    def test_a_stamp_that_is_not_a_version_at_all_is_refused(self):
        with pytest.raises(ScenarioFormatError):
            f.check_scenario_format(general('one'), 'scenario')


class TestTheOverride:
    """The escape hatch is deliberate, explicit and loud."""

    def test_an_incompatible_scenario_is_read_when_the_caller_insists(self):
        assert f.check_scenario_format({}, 'scenario', allow_incompatible=True) is None

    def test_the_override_reports_what_it_suppressed(self, capsys):
        """Silently proceeding would be worse than not checking at all."""
        f.check_scenario_format(general(CURRENT - 1), 'scenario', allow_incompatible=True)

        printed = capsys.readouterr().out
        assert 'WARNING' in printed
        assert f'version {CURRENT - 1}' in printed

    def test_a_matching_scenario_says_nothing(self, capsys):
        f.check_scenario_format(general(), 'scenario', allow_incompatible=True)

        assert capsys.readouterr().out == ''
